#!/bin/sh

PATH=$PATH:~/bin
export EDITOR=vim

# Give the terminal a touch of spring
man() {
        env \   
            LESS_TERMCAP_mb=$(printf "\e[1;31m") \
            LESS_TERMCAP_md=$(printf "\e[1;31m") \
            LESS_TERMCAP_me=$(printf "\e[0m") \
            LESS_TERMCAP_se=$(printf "\e[0m") \
            LESS_TERMCAP_so=$(printf "\e[1;44;33m") \
            LESS_TERMCAP_ue=$(printf "\e[0m") \
            LESS_TERMCAP_us=$(printf "\e[1;32m") \
                man "$@"
}

alias ls='ls --color=auto'
alias dir='dir --color=auto'
alias grep='grep --colour=auto'

